package testhelpers

import (
	"context"
	"fmt"
	"time"

	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/wait"
)

// OracleTestContainer Oracleテストコンテナの設定
type OracleTestContainer struct {
	Container testcontainers.Container
	Host      string
	Port      int
	Database  string // サービス名
	Username  string
	Password  string
}

// SetupOracleContainer Oracleテストコンテナをセットアップする
// Oracle XE (Express Edition) を使用
func SetupOracleContainer(ctx context.Context) (*OracleTestContainer, error) {
	// Oracle XE 21c を使用（軽量版）
	// gvenzl/oracle-xe は公式に近い軽量イメージ
	req := testcontainers.ContainerRequest{
		Image:        "gvenzl/oracle-xe:21-slim",
		ExposedPorts: []string{"1521/tcp"},
		Env: map[string]string{
			"ORACLE_PASSWORD": "testpass",
		},
		WaitingFor: wait.ForLog("DATABASE IS READY TO USE!").
			WithStartupTimeout(300 * time.Second), // Oracleは起動に時間がかかる
	}

	container, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{
		ContainerRequest: req,
		Started:          true,
	})
	if err != nil {
		return nil, fmt.Errorf("oracleコンテナの起動に失敗しました: %w", err)
	}

	host, err := container.Host(ctx)
	if err != nil {
		return nil, fmt.Errorf("ホストの取得に失敗しました: %w", err)
	}

	mappedPort, err := container.MappedPort(ctx, "1521")
	if err != nil {
		return nil, fmt.Errorf("ポートの取得に失敗しました: %w", err)
	}

	return &OracleTestContainer{
		Container: container,
		Host:      host,
		Port:      mappedPort.Int(),
		Database:  "XEPDB1", // Oracle XEのデフォルトPDB
		Username:  "system",
		Password:  "testpass",
	}, nil
}

// Terminate コンテナを終了する
func (o *OracleTestContainer) Terminate(ctx context.Context) error {
	if o.Container != nil {
		return o.Container.Terminate(ctx)
	}
	return nil
}

// CreateTestTable テスト用のテーブルを作成する
func (o *OracleTestContainer) CreateTestTable(ctx context.Context) error {
	connStr := fmt.Sprintf("oracle://%s:%s@%s:%d/%s",
		o.Username, o.Password, o.Host, o.Port, o.Database)

	db, err := openTestDB("oracle", connStr)
	if err != nil {
		return err
	}
	defer func() { _ = db.Close() }()

	// 既存のテーブルを削除（存在する場合）
	_, _ = db.ExecContext(ctx, `DROP TABLE test_table`)

	// テストテーブルを作成
	_, err = db.ExecContext(ctx, `
		CREATE TABLE test_table (
			id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name VARCHAR2(100) NOT NULL,
			email VARCHAR2(255),
			age NUMBER(10),
			salary NUMBER(10, 2),
			is_active NUMBER(1) DEFAULT 1,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	`)
	if err != nil {
		return fmt.Errorf("テストテーブルの作成に失敗しました: %w", err)
	}

	// テストデータを挿入
	_, err = db.ExecContext(ctx, `
		INSERT INTO test_table (name, email, age, salary, is_active) VALUES
		('Alice', 'alice@example.com', 30, 50000.00, 1)
	`)
	if err != nil {
		return fmt.Errorf("テストデータの挿入に失敗しました(1): %w", err)
	}

	_, err = db.ExecContext(ctx, `
		INSERT INTO test_table (name, email, age, salary, is_active) VALUES
		('Bob', 'bob@example.com', 25, 45000.00, 1)
	`)
	if err != nil {
		return fmt.Errorf("テストデータの挿入に失敗しました(2): %w", err)
	}

	_, err = db.ExecContext(ctx, `
		INSERT INTO test_table (name, email, age, salary, is_active) VALUES
		('Charlie', 'charlie@example.com', 35, 60000.00, 0)
	`)
	if err != nil {
		return fmt.Errorf("テストデータの挿入に失敗しました(3): %w", err)
	}

	return nil
}

// CreateTestView テスト用のビューを作成する
func (o *OracleTestContainer) CreateTestView(ctx context.Context) error {
	connStr := fmt.Sprintf("oracle://%s:%s@%s:%d/%s",
		o.Username, o.Password, o.Host, o.Port, o.Database)

	db, err := openTestDB("oracle", connStr)
	if err != nil {
		return err
	}
	defer func() { _ = db.Close() }()

	// 既存のビューを削除（存在する場合）
	_, _ = db.ExecContext(ctx, `DROP VIEW test_view`)

	// テストビューを作成（アクティブなユーザーのみを表示）
	_, err = db.ExecContext(ctx, `
		CREATE VIEW test_view AS
		SELECT id, name, email, age, salary
		FROM test_table
		WHERE is_active = 1
	`)
	if err != nil {
		return fmt.Errorf("テストビューの作成に失敗しました: %w", err)
	}

	return nil
}
